### ISSUE TITLE
Fork ABCSharp?

### ISSUE THREAD

**Issue by ThierryBachmann** [matthewcpp/ABCSharp#1]
Hello
Thank for your ABCSharp!
I wanted writing a C# to convert ABC to MIDI and I found your repo. 
Of course I will need to add some stuffs to your parser (mainly parsing the %%MIDI directive). 
So, I need to fork, could you advice me if it's better to fork from master or from slurs branch?
Have you some commit waiting?

Regards
Thierry

**Comment by matthewcpp** [comment]
Hi Thierry,

Thanks for your interest in this library.  It has a pretty minimal feature set, but I hope what is there suits your purpose.  I went ahead and merged in the slurs branch to master.  I was doing some work on that branch to support my unity package which depends on this library, but just hadn't merged it back in yet.   I would go ahead and just fork from the master branch now!

Thanks and good luck!
Matthew

**Comment by ThierryBachmann** [comment]
Not so minimal! You have done a lot with a very good and pragmatic approach. It will save me time. It will be (almost) easy to extend, even if ABC is quite complex ... from an algo point of view! 
I also saw your repo ABC Music Notation in Unity, very impressive.
I'm the publisher for [Maestro MPTK in Unity](https://assetstore.unity.com/packages/tools/audio/maestro-midi-player-tool-kit-free-107994), sometimes people ask me if Maestro can create music notation, of course not. Now I will refer them to your repo (or Unity package).
Thank you for your prompt reply.
Thierry

**Comment by ThierryBachmann** [comment]
got it, thank

**Comment by cihadturhan** [comment]
Hello @ThierryBachmann, what a coincidence!

I'm a Maestro MPTK Pro user and I just wonder if there is a way to display a MIDI as sheet music.
I've already started working on it, but I have no idea how to translate ties and slurs from MIDI -> Sheet Music.

Did you have any progress on this?
